services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: ecommerce_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - b2b-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-emagos
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    networks:
      - b2b-network
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: ecommerce_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - b2b-network

  identity-api:
    build:
      context: .
      dockerfile: src/Domains/Identity/Identity.Api/Dockerfile
    container_name: identity-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=ecommerce_postgres;Database=ecommerce_db;Username=admin;Password=admin123
      - RabbitMQ__ConnectionString=amqp://admin:admin123@ecommerce_rabbitmq:5672/
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - b2b-network

  catalog-api:
    build:
      context: .
      dockerfile: src/Domains/Catalog/Catalog.Api/Dockerfile
    container_name: catalog-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=ecommerce_postgres;Database=ecommerce_db;Username=admin;Password=admin123
      - RabbitMQ__ConnectionString=amqp://admin:admin123@ecommerce_rabbitmq:5672/
    ports:
      - "5002:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - b2b-network

  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile # Verifique se o arquivo está aqui
    container_name: b2b-gateway
    ports:
      - "8000:8080"
    depends_on:
      - identity-api
      - catalog-api
    networks:
      - b2b-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  b2b-network:
    driver: bridge