services:
  postgres:
    image: postgres:latest
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-emagos
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce_rabbitmq
    ports:
      - "5672:5672"   # Porta para comunicação
      - "15672:15672" # Porta para painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
  rabbitmq_data: