CREATE TABLE Users (
    Id UUID PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Active BOOLEAN DEFAULT TRUE,
    Role VARCHAR(50) NOT NULL
);